"""Generate a styled one-page PDF summary of a job-fit analysis."""

from __future__ import annotations

from datetime import datetime
import re
from fpdf import FPDF

SECTION_KEYS = [
    "ATS SUMMARY:",
    "MATCHED KEYWORDS:",
    "MISSING KEYWORDS:",
    "REWRITE SUGGESTIONS:",
    "COVER LETTER:",
]

# Brand palette (RGB)
NAVY = (30, 58, 95)
SLATE = (71, 85, 105)
LIGHT_BG = (243, 244, 246)
WHITE = (255, 255, 255)
GREEN = (34, 197, 94)
AMBER = (249, 115, 22)
RED = (239, 68, 68)
BAR_BG = (229, 231, 235)

_UNICODE_REPLACEMENTS = {
    "\u2026": "...",  # ellipsis
    "\u2013": "-",    # en dash
    "\u2014": "-",    # em dash
    "\u2018": "'",    # left single quote
    "\u2019": "'",    # right single quote
    "\u201c": '"',    # left double quote
    "\u201d": '"',    # right double quote
    "\u2022": "-",    # bullet
    "\u00a0": " ",    # non-breaking space
}


def _pdf_text(text: str) -> str:
    """Normalize text for Helvetica/latin-1 PDF output."""
    if not text:
        return ""
    for src, dst in _UNICODE_REPLACEMENTS.items():
        text = text.replace(src, dst)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def parse_section(output: str, key: str) -> str | None:
    if key not in output:
        return None
    text = output.split(key, 1)[1]
    for other in SECTION_KEYS:
        if other != key and other in text:
            text = text.split(other, 1)[0]
    return text.strip()


def extract_ats_score(text: str, override: int | None = None) -> int | None:
    if override is not None and 0 <= override <= 100:
        return override
    explicit = re.search(
        r"ATS\s+Match\s+Score:\s*(\d{1,3})\s*/\s*100",
        text or "",
        re.IGNORECASE,
    )
    if explicit:
        score = int(explicit.group(1))
        if 0 <= score <= 100:
            return score
    for match in re.finditer(r"\b(\d{1,3})\b", text or ""):
        score = int(match.group(1))
        if 0 <= score <= 100:
            return score
    return None


def _score_color(score: int | None) -> tuple[int, int, int]:
    if score is None:
        return SLATE
    if score >= 70:
        return GREEN
    if score >= 50:
        return AMBER
    return RED


def _split_items(text: str) -> list[str]:
    if not text:
        return []
    parts = re.split(r"[\n,;]+", text)
    items = []
    for part in parts:
        cleaned = re.sub(r"^[\s\-•*]+", "", part.strip())
        if cleaned:
            items.append(cleaned)
    return items


def _split_bullets(text: str) -> list[str]:
    if not text:
        return []
    lines = []
    for line in text.splitlines():
        cleaned = re.sub(r"^[\s\-•*]+", "", line.strip())
        if cleaned:
            lines.append(cleaned)
    return lines


def _truncate(text: str, max_len: int = 120) -> str:
    """Shorten header metadata only (single-line fields)."""
    text = re.sub(r"\s+", " ", text or "").strip()
    if len(text) <= max_len:
        return text
    return text[: max_len - 3].rsplit(" ", 1)[0] + "..."


class JobFitReportPDF(FPDF):
    def __init__(self, resume_name: str, job_snippet: str):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.resume_name = _pdf_text(resume_name or "Resume")
        self.job_snippet = _pdf_text(_truncate(job_snippet, 120))
        self.set_auto_page_break(auto=True, margin=22)
        self.set_margins(14, 14, 14)

    def header(self):
        self.set_fill_color(*NAVY)
        self.rect(0, 0, 210, 28, "F")
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 18)
        self.set_xy(14, 8)
        self.cell(0, 8, "Job Fit Analysis Report", ln=True)
        self.set_font("Helvetica", "", 9)
        self.set_xy(14, 17)
        meta = f"Resume: {self.resume_name}"
        if self.job_snippet:
            meta += f"  |  Role: {self.job_snippet}"
        self.cell(0, 5, meta, ln=True)
        self.set_text_color(0, 0, 0)
        self.set_y(32)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*SLATE)
        generated = datetime.now().strftime("%B %d, %Y")
        self.cell(
            0,
            5,
            f"Generated by AI Job-Fit Analyzer  |  {generated}  |  For personal use only",
            align="C",
        )


def build_pdf_report(
    output_text: str,
    resume_filename: str = "",
    job_description: str = "",
    ats_score: int | None = None,
) -> bytes:
    """Build a one-page PDF bytes payload from raw LLM analysis output."""
    ats_summary = parse_section(output_text, "ATS SUMMARY:") or ""
    matched = parse_section(output_text, "MATCHED KEYWORDS:") or ""
    missing = parse_section(output_text, "MISSING KEYWORDS:") or ""
    suggestions = parse_section(output_text, "REWRITE SUGGESTIONS:") or ""
    cover_letter = parse_section(output_text, "COVER LETTER:") or ""

    score = extract_ats_score(ats_summary, override=ats_score)
    resume_name = _pdf_text(resume_filename.replace(".pdf", "") if resume_filename else "Resume")
    job_snippet = _truncate(job_description.splitlines()[0] if job_description else "", 120)

    pdf = JobFitReportPDF(resume_name=resume_name, job_snippet=job_snippet)
    pdf.add_page()

    usable_w = pdf.w - pdf.l_margin - pdf.r_margin

    # ── ATS score block ──────────────────────────────────────
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 6, "ATS Match Score", ln=True)

    score_label = f"{score} / 100" if score is not None else "N/A"
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(*_score_color(score))
    pdf.cell(40, 10, score_label)

    # Score progress bar
    bar_x = pdf.l_margin + 44
    bar_y = pdf.get_y() + 2
    bar_w = usable_w - 48
    bar_h = 6
    pdf.set_fill_color(*BAR_BG)
    pdf.rect(bar_x, bar_y, bar_w, bar_h, "F")
    if score is not None:
        pdf.set_fill_color(*_score_color(score))
        pdf.rect(bar_x, bar_y, bar_w * (score / 100), bar_h, "F")

    pdf.ln(8)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(55, 65, 81)
    pdf.multi_cell(usable_w, 4.5, _pdf_text(ats_summary))
    pdf.ln(4)

    # ── Keywords (two columns) ───────────────────────────────
    col_gap = 6
    col_w = (usable_w - col_gap) / 2
    y_start = pdf.get_y()

    def keyword_column(x: float, y: float, title: str, items: list[str], accent: tuple):
        pdf.set_xy(x, y)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*accent)
        pdf.cell(col_w, 6, title, ln=True)
        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_text_color(31, 41, 55)
        if items:
            for item in items:
                pdf.set_x(x)
                pdf.multi_cell(col_w, 5, f"- {_pdf_text(item)}")
        else:
            pdf.set_x(x)
            pdf.multi_cell(col_w, 5, "None identified.")
        return pdf.get_y()

    matched_items = _split_items(matched)
    missing_items = _split_items(missing)

    left_bottom = keyword_column(pdf.l_margin,                   y_start, "Matched Keywords", matched_items, GREEN)
    right_bottom = keyword_column(pdf.l_margin + col_w + col_gap, y_start, "Missing Keywords", missing_items, RED)

    col_bottom = max(left_bottom, right_bottom)
    pdf.set_y(col_bottom + 5)

    # ── Rewrite suggestions ──────────────────────────────────
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 6, "Top Resume Improvements", ln=True)
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(31, 41, 55)
    for idx, suggestion in enumerate(_split_bullets(suggestions), start=1):
        pdf.multi_cell(usable_w, 5.5, f"{idx}. {_pdf_text(suggestion)}")
        pdf.ln(0.5)

    pdf.ln(2)

    # ── Cover letter ───────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 6, "Cover Letter", ln=True)
    pdf.set_font("Helvetica", "I", 8.5)
    pdf.set_text_color(55, 65, 81)
    pdf.multi_cell(usable_w, 4.2, _pdf_text(cover_letter))

    pdf_bytes = pdf.output(dest="S")
    if isinstance(pdf_bytes, str):
        pdf_bytes = pdf_bytes.encode("latin-1")
    return bytes(pdf_bytes)
